### ISSUE TITLE
Adapt script so num_rows is an argument

### ISSUE THREAD

**Issue by archaeogeek** [AstunTechnology/gemini_csv_import#3]
Currently you need to edit the script before running, to put in the number of rows, which is annoying. The script should be adjusted so that it can be run with the number of rows as an argument, eg `metadata_import.py --rows=17`

**Comment by mtravis** [comment]
Tried using sys.argv to pass an argument but the Unittest function does not like this.

**Comment by mtravis** [comment]
https://tellthemuserstories.wordpress.com/2013/01/19/python-unittest-command-line-argument/

**Comment by alexarobu** [comment]
resolved by https://github.com/AstunTechnology/gemini_csv_import/commit/76befa41246a2c57a5756a147c77e72f87f8383b

it's not exactly an argument because as Matt's comment highlights there is an issue with unittest not exactly appreciating command-line arguments, but there is now a prompt to the user asking how many lines need to be parsed which can take either a number or "all".

**Comment by alexarobu** [comment]
will try to improve this to take either a command-line argument or an input

**Comment by alexarobu** [comment]
fixed by https://github.com/AstunTechnology/gemini_csv_import/commit/520967bc19646c604f360a71258fbc3f3042d3fc

it now takes either command-line arguments, or, if none is passed, it requests user input.
